### ISSUE TITLE
Mass matrix and timestep

### ISSUE THREAD

**Issue by ahunter16** [LegendGraphics/FastMassSpring#3]
Thanks for writing this framework. My only issue with it is that I can't see how the mass matrix and timestep mentioned in the paper fit in. It appears that, in this implementation, the system matrix is just the weighted laplacian (L) instead of being (M + h^2L), where M is the Mass matrix and h is the fixed timestep. 
Am I getting this wrong, or are these things that the person using the framework should implement?

**Comment by marlinilram** [comment]
Hi @ahunter16 , your observation is right. This is not a fully implementation for Fast Mass Spring System. The main purpose of this simple framework is to support a kind of mesh optimization with different quadratic constraints on vertices (you can refer to "Shape-Up: Shaping Discrete Geometry with Projections" if you are interested. :-)). 

As to your question, if you still want to use this framework:
Gradient on x of 1/2xT(M+h^2L)x-h^2xTJd+xTb is (M+h^2L)x=h^2Jd-b, the global step is to solve this linear system. Current FastMassSpring.cpp only solve Lx=Jd, but you can simply add a new constraint as "1/2xT(M/h^2)x+xTb" which supply the solver with system matrix M/h^2 and right hand -b/h^2. The solver will sum up the system matrix and right hand for each constraint so the final system would be the same to (M+h^2L)x=h^2Jd-b.

Hope this helps.

**Comment by ahunter16** [comment]
Thanks very much, that helps a lot!

**Comment by ahunter16** [comment]
So I have implemented your suggestion, but it is exhibiting very strange behaviour. The values in P_Opt (which is x, if I am not mistaken) become extremely small after one iteration. It appears that they have been shuffled around and divided by 900 (my timestep is 1/30, so it makes sense given that this squared is 1/900). 
Here's the new constraint:
https://pastebin.com/H4NdHNwZ

And here's the results of the test:
https://pastebin.com/U9G4c0d2

Have I misunderstood your suggestion?
Also it's worth noting that I removed the code for generating bending springs to simplify things (I'm initially just trying to use this for cloth simulation, so bending springs are less important in this case)
Thanks again.

**Comment by marlinilram** [comment]
Hi @ahunter16 Your code looks correct to me.  Can you provide more information about how you init the Solver class and the FastMassSpring class?

**Comment by ahunter16** [comment]
Hi, no problem:
https://pastebin.com/BG9W8Hj5
this->positions is a VectorXf of size 3m, and nodes is an std::vector of size m.

**Comment by marlinilram** [comment]
Hi @ahunter16 , 
1. Just want to make sure that the layout of position is like x_1, y_1, z_1, x_2, y_2, z_2, ..., x_n, y_n, z_n. And this->position is exactly same to this->vertexList, right?
2. Looks like you don't prepare the adj list for the fms constraint. It's a vector<vector< int > > with size of number of vertices. Each element stores the ids of its 1-ring neighbor faces. I added a new method so you don't have to do it yourself.
3. If you don't want bending springs, it should be set in fms constraint. fms->setkBending(0.0)

Let me know if there is other problems.

**Comment by ahunter16** [comment]
1. Yes, I have an std::vector of 3D vectors that I put into the positions list

2. I actually removed the bending constraint code, but hadn't changed the function declaration, so adjlist isn't really used. The main reason I did this was that I wasn't sure how to form the vertex-shared-faces parameter for initEdgeGraph(), is it just a representation of an adjacency matrix, where [i][j] = 1 if nodes are connected by a spring and 0 otherwise? [EDIT] must have missed the second part of your response, thanks!

Thanks again for your responses.

**Comment by ahunter16** [comment]
Thanks for adding in that method, however it hasn't really stopped the system from outputting extremely low values for the positions.
Just to be sure: P_Opt represents the positions of the vertices and not the velocities, right? 
Here are the values I get with the new modifications:
https://pastebin.com/dzJGTv2p

**Comment by ahunter16** [comment]
Sorry to pester you again, but do you have any idea why the system might be behaving like this?

**Comment by marlinilram** [comment]
Hi, @ahunter16 I read the paper again. I think we both forgot what b stands for. According to the paper "aggregated the external forces and inertia (y in Section 3) into vector b ∈ R^3m" and plug eq. 13 into eq. 8, the b vector = (-My+f_ext) which means even though there is no external force, the b vector should at least equal to -My.

I added a test SimCloth class and verified it on your data. It behaves normal now.

Best,
Lin

**Comment by ahunter16** [comment]
Aaaah, I had missed that part, as well, and assumed that b was just the external forces.
Thanks for all your help, it works well now.
